package it.sinergis.sunshine.sos40.pojo;

// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Compositephenomenon generated by hbm2java
 */
@Entity
@Table(name = "compositephenomenon")
public class Compositephenomenon implements java.io.Serializable {
	
	private long id;
	
	public Compositephenomenon() {
	}
	
	public Compositephenomenon(long id) {
		this.id = id;
	}
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "observableproperty", column = @Column(name = "childobservablepropertyid", nullable = false)),
			@AttributeOverride(name = "observableproperty_1", column = @Column(name = "parentobservablepropertyid", nullable = false)) })
	public long getId() {
		return this.id;
	}
	
	public void setId(long id) {
		this.id = id;
	}
	
}
