package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Observationconstellation generated by hbm2java
 */
@Entity
@Table(name="observationconstellation"
    , uniqueConstraints = @UniqueConstraint(columnNames={"observablepropertyid", "procedureid", "offeringid"}) 
)
public class Observationconstellation  implements java.io.Serializable {


     private long observationconstellationid;
     private Observationtype observationtype;
     private Offering offering;
     private Procedure procedure;
     private Observableproperty observableproperty;
     private char deleted;
     private char hiddenchild;

    public Observationconstellation() {
    }

	
    public Observationconstellation(long observationconstellationid, Offering offering, Procedure procedure, Observableproperty observableproperty, char deleted, char hiddenchild) {
        this.observationconstellationid = observationconstellationid;
        this.offering = offering;
        this.procedure = procedure;
        this.observableproperty = observableproperty;
        this.deleted = deleted;
        this.hiddenchild = hiddenchild;
    }
    public Observationconstellation(long observationconstellationid, Observationtype observationtype, Offering offering, Procedure procedure, Observableproperty observableproperty, char deleted, char hiddenchild) {
       this.observationconstellationid = observationconstellationid;
       this.observationtype = observationtype;
       this.offering = offering;
       this.procedure = procedure;
       this.observableproperty = observableproperty;
       this.deleted = deleted;
       this.hiddenchild = hiddenchild;
    }
   
     @Id 

    
    @Column(name="observationconstellationid", unique=true, nullable=false)
    public long getObservationconstellationid() {
        return this.observationconstellationid;
    }
    
    public void setObservationconstellationid(long observationconstellationid) {
        this.observationconstellationid = observationconstellationid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="observationtypeid")
    public Observationtype getObservationtype() {
        return this.observationtype;
    }
    
    public void setObservationtype(Observationtype observationtype) {
        this.observationtype = observationtype;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="offeringid", nullable=false)
    public Offering getOffering() {
        return this.offering;
    }
    
    public void setOffering(Offering offering) {
        this.offering = offering;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="procedureid", nullable=false)
    public Procedure getProcedure() {
        return this.procedure;
    }
    
    public void setProcedure(Procedure procedure) {
        this.procedure = procedure;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="observablepropertyid", nullable=false)
    public Observableproperty getObservableproperty() {
        return this.observableproperty;
    }
    
    public void setObservableproperty(Observableproperty observableproperty) {
        this.observableproperty = observableproperty;
    }

    
    @Column(name="deleted", nullable=false, length=1)
    public char getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(char deleted) {
        this.deleted = deleted;
    }

    
    @Column(name="hiddenchild", nullable=false, length=1)
    public char getHiddenchild() {
        return this.hiddenchild;
    }
    
    public void setHiddenchild(char hiddenchild) {
        this.hiddenchild = hiddenchild;
    }




}


