package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Observationtype generated by hbm2java
 */
@Entity
@Table(name="observationtype"
    , uniqueConstraints = @UniqueConstraint(columnNames="observationtype") 
)
public class Observationtype  implements java.io.Serializable {


     private long observationtypeid;
     private String observationtype;
     private Set offeringallowedobservationtypes = new HashSet(0);
     private Set observationconstellations = new HashSet(0);

    public Observationtype() {
    }

	
    public Observationtype(long observationtypeid, String observationtype) {
        this.observationtypeid = observationtypeid;
        this.observationtype = observationtype;
    }
    public Observationtype(long observationtypeid, String observationtype, Set offeringallowedobservationtypes, Set observationconstellations) {
       this.observationtypeid = observationtypeid;
       this.observationtype = observationtype;
       this.offeringallowedobservationtypes = offeringallowedobservationtypes;
       this.observationconstellations = observationconstellations;
    }
   
     @Id 

    
    @Column(name="observationtypeid", unique=true, nullable=false)
    public long getObservationtypeid() {
        return this.observationtypeid;
    }
    
    public void setObservationtypeid(long observationtypeid) {
        this.observationtypeid = observationtypeid;
    }

    
    @Column(name="observationtype", unique=true, nullable=false)
    public String getObservationtype() {
        return this.observationtype;
    }
    
    public void setObservationtype(String observationtype) {
        this.observationtype = observationtype;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unresolved")
    public Set getOfferingallowedobservationtypes() {
        return this.offeringallowedobservationtypes;
    }
    
    public void setOfferingallowedobservationtypes(Set offeringallowedobservationtypes) {
        this.offeringallowedobservationtypes = offeringallowedobservationtypes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="observationtype")
    public Set getObservationconstellations() {
        return this.observationconstellations;
    }
    
    public void setObservationconstellations(Set observationconstellations) {
        this.observationconstellations = observationconstellations;
    }




}


