package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Offering generated by hbm2java
 */
@Entity
@Table(name="offering"
    , uniqueConstraints = @UniqueConstraint(columnNames="identifier") 
)
public class Offering  implements java.io.Serializable {


     private long offeringid;
     private char hibernatediscriminator;
     private String identifier;
     private String name;
     private Set offeringallowedfeaturetypes = new HashSet(0);
     private Set offeringhasrelatedfeatures = new HashSet(0);
     private Set observationhasofferings = new HashSet(0);
     private Set offeringallowedobservationtypes = new HashSet(0);
     private Set observationconstellations = new HashSet(0);
     private Set resulttemplates = new HashSet(0);

    public Offering() {
    }

	
    public Offering(long offeringid, char hibernatediscriminator, String identifier) {
        this.offeringid = offeringid;
        this.hibernatediscriminator = hibernatediscriminator;
        this.identifier = identifier;
    }
    public Offering(long offeringid, char hibernatediscriminator, String identifier, String name, Set offeringallowedfeaturetypes, Set offeringhasrelatedfeatures, Set observationhasofferings, Set offeringallowedobservationtypes, Set observationconstellations, Set resulttemplates) {
       this.offeringid = offeringid;
       this.hibernatediscriminator = hibernatediscriminator;
       this.identifier = identifier;
       this.name = name;
       this.offeringallowedfeaturetypes = offeringallowedfeaturetypes;
       this.offeringhasrelatedfeatures = offeringhasrelatedfeatures;
       this.observationhasofferings = observationhasofferings;
       this.offeringallowedobservationtypes = offeringallowedobservationtypes;
       this.observationconstellations = observationconstellations;
       this.resulttemplates = resulttemplates;
    }
   
     @Id 

    
    @Column(name="offeringid", unique=true, nullable=false)
    public long getOfferingid() {
        return this.offeringid;
    }
    
    public void setOfferingid(long offeringid) {
        this.offeringid = offeringid;
    }

    
    @Column(name="hibernatediscriminator", nullable=false, length=1)
    public char getHibernatediscriminator() {
        return this.hibernatediscriminator;
    }
    
    public void setHibernatediscriminator(char hibernatediscriminator) {
        this.hibernatediscriminator = hibernatediscriminator;
    }

    
    @Column(name="identifier", unique=true, nullable=false)
    public String getIdentifier() {
        return this.identifier;
    }
    
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unresolved")
    public Set getOfferingallowedfeaturetypes() {
        return this.offeringallowedfeaturetypes;
    }
    
    public void setOfferingallowedfeaturetypes(Set offeringallowedfeaturetypes) {
        this.offeringallowedfeaturetypes = offeringallowedfeaturetypes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unresolved")
    public Set getOfferinghasrelatedfeatures() {
        return this.offeringhasrelatedfeatures;
    }
    
    public void setOfferinghasrelatedfeatures(Set offeringhasrelatedfeatures) {
        this.offeringhasrelatedfeatures = offeringhasrelatedfeatures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unresolved")
    public Set getObservationhasofferings() {
        return this.observationhasofferings;
    }
    
    public void setObservationhasofferings(Set observationhasofferings) {
        this.observationhasofferings = observationhasofferings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unresolved")
    public Set getOfferingallowedobservationtypes() {
        return this.offeringallowedobservationtypes;
    }
    
    public void setOfferingallowedobservationtypes(Set offeringallowedobservationtypes) {
        this.offeringallowedobservationtypes = offeringallowedobservationtypes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="offering")
    public Set getObservationconstellations() {
        return this.observationconstellations;
    }
    
    public void setObservationconstellations(Set observationconstellations) {
        this.observationconstellations = observationconstellations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="offering")
    public Set getResulttemplates() {
        return this.resulttemplates;
    }
    
    public void setResulttemplates(Set resulttemplates) {
        this.resulttemplates = resulttemplates;
    }




}


