package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Parameter generated by hbm2java
 */
@Entity
@Table(name="parameter"
)
public class Parameter  implements java.io.Serializable {


     private long parameterid;
     private long observationid;
     private String definition;
     private String title;
     private long value;

    public Parameter() {
    }

	
    public Parameter(long parameterid, long observationid, String definition, long value) {
        this.parameterid = parameterid;
        this.observationid = observationid;
        this.definition = definition;
        this.value = value;
    }
    public Parameter(long parameterid, long observationid, String definition, String title, long value) {
       this.parameterid = parameterid;
       this.observationid = observationid;
       this.definition = definition;
       this.title = title;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="parameterid", unique=true, nullable=false)
    public long getParameterid() {
        return this.parameterid;
    }
    
    public void setParameterid(long parameterid) {
        this.parameterid = parameterid;
    }

    
    @Column(name="observationid", nullable=false)
    public long getObservationid() {
        return this.observationid;
    }
    
    public void setObservationid(long observationid) {
        this.observationid = observationid;
    }

    
    @Column(name="definition", nullable=false)
    public String getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(String definition) {
        this.definition = definition;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="value", nullable=false)
    public long getValue() {
        return this.value;
    }
    
    public void setValue(long value) {
        this.value = value;
    }




}


