package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Procedure generated by hbm2java
 */
@Entity
@Table(name="procedure"
    , uniqueConstraints = @UniqueConstraint(columnNames="identifier") 
)
public class Procedure  implements java.io.Serializable {


     private long procedureid;
     private Proceduredescriptionformat proceduredescriptionformat;
     private char hibernatediscriminator;
     private String identifier;
     private char deleted;
     private String descriptionfile;
     private Set resulttemplates = new HashSet(0);
     private Set observationconstellations = new HashSet(0);
     private Set validproceduretimes = new HashSet(0);
     private Set sensorsystemsForChildsensorid = new HashSet(0);
     private Set sensorsystemsForParentsensorid = new HashSet(0);
     private Set serieses = new HashSet(0);

    public Procedure() {
    }

	
    public Procedure(long procedureid, Proceduredescriptionformat proceduredescriptionformat, char hibernatediscriminator, String identifier, char deleted) {
        this.procedureid = procedureid;
        this.proceduredescriptionformat = proceduredescriptionformat;
        this.hibernatediscriminator = hibernatediscriminator;
        this.identifier = identifier;
        this.deleted = deleted;
    }
    public Procedure(long procedureid, Proceduredescriptionformat proceduredescriptionformat, char hibernatediscriminator, String identifier, char deleted, String descriptionfile, Set resulttemplates, Set observationconstellations, Set validproceduretimes, Set sensorsystemsForChildsensorid, Set sensorsystemsForParentsensorid, Set serieses) {
       this.procedureid = procedureid;
       this.proceduredescriptionformat = proceduredescriptionformat;
       this.hibernatediscriminator = hibernatediscriminator;
       this.identifier = identifier;
       this.deleted = deleted;
       this.descriptionfile = descriptionfile;
       this.resulttemplates = resulttemplates;
       this.observationconstellations = observationconstellations;
       this.validproceduretimes = validproceduretimes;
       this.sensorsystemsForChildsensorid = sensorsystemsForChildsensorid;
       this.sensorsystemsForParentsensorid = sensorsystemsForParentsensorid;
       this.serieses = serieses;
    }
   
     @Id 

    
    @Column(name="procedureid", unique=true, nullable=false)
    public long getProcedureid() {
        return this.procedureid;
    }
    
    public void setProcedureid(long procedureid) {
        this.procedureid = procedureid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proceduredescriptionformatid", nullable=false)
    public Proceduredescriptionformat getProceduredescriptionformat() {
        return this.proceduredescriptionformat;
    }
    
    public void setProceduredescriptionformat(Proceduredescriptionformat proceduredescriptionformat) {
        this.proceduredescriptionformat = proceduredescriptionformat;
    }

    
    @Column(name="hibernatediscriminator", nullable=false, length=1)
    public char getHibernatediscriminator() {
        return this.hibernatediscriminator;
    }
    
    public void setHibernatediscriminator(char hibernatediscriminator) {
        this.hibernatediscriminator = hibernatediscriminator;
    }

    
    @Column(name="identifier", unique=true, nullable=false)
    public String getIdentifier() {
        return this.identifier;
    }
    
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    
    @Column(name="deleted", nullable=false, length=1)
    public char getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(char deleted) {
        this.deleted = deleted;
    }

    
    @Column(name="descriptionfile")
    public String getDescriptionfile() {
        return this.descriptionfile;
    }
    
    public void setDescriptionfile(String descriptionfile) {
        this.descriptionfile = descriptionfile;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedure")
    public Set getResulttemplates() {
        return this.resulttemplates;
    }
    
    public void setResulttemplates(Set resulttemplates) {
        this.resulttemplates = resulttemplates;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedure")
    public Set getObservationconstellations() {
        return this.observationconstellations;
    }
    
    public void setObservationconstellations(Set observationconstellations) {
        this.observationconstellations = observationconstellations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedure")
    public Set getValidproceduretimes() {
        return this.validproceduretimes;
    }
    
    public void setValidproceduretimes(Set validproceduretimes) {
        this.validproceduretimes = validproceduretimes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unresolved")
    public Set getSensorsystemsForChildsensorid() {
        return this.sensorsystemsForChildsensorid;
    }
    
    public void setSensorsystemsForChildsensorid(Set sensorsystemsForChildsensorid) {
        this.sensorsystemsForChildsensorid = sensorsystemsForChildsensorid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unresolved")
    public Set getSensorsystemsForParentsensorid() {
        return this.sensorsystemsForParentsensorid;
    }
    
    public void setSensorsystemsForParentsensorid(Set sensorsystemsForParentsensorid) {
        this.sensorsystemsForParentsensorid = sensorsystemsForParentsensorid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedure")
    public Set getSerieses() {
        return this.serieses;
    }
    
    public void setSerieses(Set serieses) {
        this.serieses = serieses;
    }




}


