package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Resulttemplate generated by hbm2java
 */
@Entity
@Table(name="resulttemplate"
)
public class Resulttemplate  implements java.io.Serializable {


     private long resulttemplateid;
     private Offering offering;
     private Procedure procedure;
     private Observableproperty observableproperty;
     private Featureofinterest featureofinterest;
     private String identifier;
     private String resultstructure;
     private String resultencoding;

    public Resulttemplate() {
    }

    public Resulttemplate(long resulttemplateid, Offering offering, Procedure procedure, Observableproperty observableproperty, Featureofinterest featureofinterest, String identifier, String resultstructure, String resultencoding) {
       this.resulttemplateid = resulttemplateid;
       this.offering = offering;
       this.procedure = procedure;
       this.observableproperty = observableproperty;
       this.featureofinterest = featureofinterest;
       this.identifier = identifier;
       this.resultstructure = resultstructure;
       this.resultencoding = resultencoding;
    }
   
     @Id 

    
    @Column(name="resulttemplateid", unique=true, nullable=false)
    public long getResulttemplateid() {
        return this.resulttemplateid;
    }
    
    public void setResulttemplateid(long resulttemplateid) {
        this.resulttemplateid = resulttemplateid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="offeringid", nullable=false)
    public Offering getOffering() {
        return this.offering;
    }
    
    public void setOffering(Offering offering) {
        this.offering = offering;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="procedureid", nullable=false)
    public Procedure getProcedure() {
        return this.procedure;
    }
    
    public void setProcedure(Procedure procedure) {
        this.procedure = procedure;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="observablepropertyid", nullable=false)
    public Observableproperty getObservableproperty() {
        return this.observableproperty;
    }
    
    public void setObservableproperty(Observableproperty observableproperty) {
        this.observableproperty = observableproperty;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="featureofinterestid", nullable=false)
    public Featureofinterest getFeatureofinterest() {
        return this.featureofinterest;
    }
    
    public void setFeatureofinterest(Featureofinterest featureofinterest) {
        this.featureofinterest = featureofinterest;
    }

    
    @Column(name="identifier", nullable=false)
    public String getIdentifier() {
        return this.identifier;
    }
    
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    
    @Column(name="resultstructure", nullable=false)
    public String getResultstructure() {
        return this.resultstructure;
    }
    
    public void setResultstructure(String resultstructure) {
        this.resultstructure = resultstructure;
    }

    
    @Column(name="resultencoding", nullable=false)
    public String getResultencoding() {
        return this.resultencoding;
    }
    
    public void setResultencoding(String resultencoding) {
        this.resultencoding = resultencoding;
    }




}


