package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Series generated by hbm2java
 */
@Entity
@Table(name="series"
    , uniqueConstraints = @UniqueConstraint(columnNames={"featureofinterestid", "observablepropertyid", "procedureid"}) 
)
public class Series  implements java.io.Serializable {


     private long seriesid;
     private Procedure procedure;
     private Observableproperty observableproperty;
     private Featureofinterest featureofinterest;
     private char deleted;
     private Set observations = new HashSet(0);

    public Series() {
    }

	
    public Series(long seriesid, Procedure procedure, Observableproperty observableproperty, Featureofinterest featureofinterest, char deleted) {
        this.seriesid = seriesid;
        this.procedure = procedure;
        this.observableproperty = observableproperty;
        this.featureofinterest = featureofinterest;
        this.deleted = deleted;
    }
    public Series(long seriesid, Procedure procedure, Observableproperty observableproperty, Featureofinterest featureofinterest, char deleted, Set observations) {
       this.seriesid = seriesid;
       this.procedure = procedure;
       this.observableproperty = observableproperty;
       this.featureofinterest = featureofinterest;
       this.deleted = deleted;
       this.observations = observations;
    }
   
     @Id 

    
    @Column(name="seriesid", unique=true, nullable=false)
    public long getSeriesid() {
        return this.seriesid;
    }
    
    public void setSeriesid(long seriesid) {
        this.seriesid = seriesid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="procedureid", nullable=false)
    public Procedure getProcedure() {
        return this.procedure;
    }
    
    public void setProcedure(Procedure procedure) {
        this.procedure = procedure;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="observablepropertyid", nullable=false)
    public Observableproperty getObservableproperty() {
        return this.observableproperty;
    }
    
    public void setObservableproperty(Observableproperty observableproperty) {
        this.observableproperty = observableproperty;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="featureofinterestid", nullable=false)
    public Featureofinterest getFeatureofinterest() {
        return this.featureofinterest;
    }
    
    public void setFeatureofinterest(Featureofinterest featureofinterest) {
        this.featureofinterest = featureofinterest;
    }

    
    @Column(name="deleted", nullable=false, length=1)
    public char getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(char deleted) {
        this.deleted = deleted;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="series")
    public Set getObservations() {
        return this.observations;
    }
    
    public void setObservations(Set observations) {
        this.observations = observations;
    }




}


