package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Spatialfilteringprofile generated by hbm2java
 */
@Entity
@Table(name="spatialfilteringprofile"
)
public class Spatialfilteringprofile  implements java.io.Serializable {


     private long spatialfilteringprofileid;
     private Observation observation;
     private String definition;
     private String title;
     private Serializable geom;

    public Spatialfilteringprofile() {
    }

	
    public Spatialfilteringprofile(long spatialfilteringprofileid, Observation observation, String definition, Serializable geom) {
        this.spatialfilteringprofileid = spatialfilteringprofileid;
        this.observation = observation;
        this.definition = definition;
        this.geom = geom;
    }
    public Spatialfilteringprofile(long spatialfilteringprofileid, Observation observation, String definition, String title, Serializable geom) {
       this.spatialfilteringprofileid = spatialfilteringprofileid;
       this.observation = observation;
       this.definition = definition;
       this.title = title;
       this.geom = geom;
    }
   
     @Id 

    
    @Column(name="spatialfilteringprofileid", unique=true, nullable=false)
    public long getSpatialfilteringprofileid() {
        return this.spatialfilteringprofileid;
    }
    
    public void setSpatialfilteringprofileid(long spatialfilteringprofileid) {
        this.spatialfilteringprofileid = spatialfilteringprofileid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="observation", nullable=false)
    public Observation getObservation() {
        return this.observation;
    }
    
    public void setObservation(Observation observation) {
        this.observation = observation;
    }

    
    @Column(name="definition", nullable=false)
    public String getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(String definition) {
        this.definition = definition;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="geom", nullable=false)
    public Serializable getGeom() {
        return this.geom;
    }
    
    public void setGeom(Serializable geom) {
        this.geom = geom;
    }




}


