package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Textvalue generated by hbm2java
 */
@Entity
@Table(name="textvalue"
)
public class Textvalue  implements java.io.Serializable {


     private long observationid;
     private String value;

    public Textvalue() {
    }

	
    public Textvalue(long observationid) {
        this.observationid = observationid;
    }
    public Textvalue(long observationid, String value) {
       this.observationid = observationid;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="observationid", unique=true, nullable=false)
    public long getObservationid() {
        return this.observationid;
    }
    
    public void setObservationid(long observationid) {
        this.observationid = observationid;
    }

    
    @Column(name="value")
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


