package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Unit generated by hbm2java
 */
@Entity
@Table(name="unit"
    , uniqueConstraints = @UniqueConstraint(columnNames="unit") 
)
public class Unit  implements java.io.Serializable {


     private long unitid;
     private String unit;
     private Set observations = new HashSet(0);

    public Unit() {
    }

	
    public Unit(long unitid, String unit) {
        this.unitid = unitid;
        this.unit = unit;
    }
    public Unit(long unitid, String unit, Set observations) {
       this.unitid = unitid;
       this.unit = unit;
       this.observations = observations;
    }
   
     @Id 

    
    @Column(name="unitid", unique=true, nullable=false)
    public long getUnitid() {
        return this.unitid;
    }
    
    public void setUnitid(long unitid) {
        this.unitid = unitid;
    }

    
    @Column(name="unit", unique=true, nullable=false)
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unit")
    public Set getObservations() {
        return this.observations;
    }
    
    public void setObservations(Set observations) {
        this.observations = observations;
    }




}


