package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Validproceduretime generated by hbm2java
 */
@Entity
@Table(name="validproceduretime"
)
public class Validproceduretime  implements java.io.Serializable {


     private long validproceduretimeid;
     private Procedure procedure;
     private Proceduredescriptionformat proceduredescriptionformat;
     private Date starttime;
     private Date endtime;
     private String descriptionxml;

    public Validproceduretime() {
    }

	
    public Validproceduretime(long validproceduretimeid, Procedure procedure, Proceduredescriptionformat proceduredescriptionformat, Date starttime, String descriptionxml) {
        this.validproceduretimeid = validproceduretimeid;
        this.procedure = procedure;
        this.proceduredescriptionformat = proceduredescriptionformat;
        this.starttime = starttime;
        this.descriptionxml = descriptionxml;
    }
    public Validproceduretime(long validproceduretimeid, Procedure procedure, Proceduredescriptionformat proceduredescriptionformat, Date starttime, Date endtime, String descriptionxml) {
       this.validproceduretimeid = validproceduretimeid;
       this.procedure = procedure;
       this.proceduredescriptionformat = proceduredescriptionformat;
       this.starttime = starttime;
       this.endtime = endtime;
       this.descriptionxml = descriptionxml;
    }
   
     @Id 

    
    @Column(name="validproceduretimeid", unique=true, nullable=false)
    public long getValidproceduretimeid() {
        return this.validproceduretimeid;
    }
    
    public void setValidproceduretimeid(long validproceduretimeid) {
        this.validproceduretimeid = validproceduretimeid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="procedureid", nullable=false)
    public Procedure getProcedure() {
        return this.procedure;
    }
    
    public void setProcedure(Procedure procedure) {
        this.procedure = procedure;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proceduredescriptionformatid", nullable=false)
    public Proceduredescriptionformat getProceduredescriptionformat() {
        return this.proceduredescriptionformat;
    }
    
    public void setProceduredescriptionformat(Proceduredescriptionformat proceduredescriptionformat) {
        this.proceduredescriptionformat = proceduredescriptionformat;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="starttime", nullable=false, length=29)
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="endtime", length=29)
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    
    @Column(name="descriptionxml", nullable=false)
    public String getDescriptionxml() {
        return this.descriptionxml;
    }
    
    public void setDescriptionxml(String descriptionxml) {
        this.descriptionxml = descriptionxml;
    }




}


