package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Blobvalue generated by hbm2java
 */
@Entity
@Table(name="blobvalue"
)
public class Blobvalue  implements java.io.Serializable {


     private long observationid;
     private Long value;

    public Blobvalue() {
    }

	
    public Blobvalue(long observationid) {
        this.observationid = observationid;
    }
    public Blobvalue(long observationid, Long value) {
       this.observationid = observationid;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="observationid", unique=true, nullable=false)
    public long getObservationid() {
        return this.observationid;
    }
    
    public void setObservationid(long observationid) {
        this.observationid = observationid;
    }

    
    @Column(name="value")
    public Long getValue() {
        return this.value;
    }
    
    public void setValue(Long value) {
        this.value = value;
    }




}


