package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Booleanvalue generated by hbm2java
 */
@Entity
@Table(name="booleanvalue"
)
public class Booleanvalue  implements java.io.Serializable {


     private long observationid;
     private Character value;

    public Booleanvalue() {
    }

	
    public Booleanvalue(long observationid) {
        this.observationid = observationid;
    }
    public Booleanvalue(long observationid, Character value) {
       this.observationid = observationid;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="observationid", unique=true, nullable=false)
    public long getObservationid() {
        return this.observationid;
    }
    
    public void setObservationid(long observationid) {
        this.observationid = observationid;
    }

    
    @Column(name="value", length=1)
    public Character getValue() {
        return this.value;
    }
    
    public void setValue(Character value) {
        this.value = value;
    }




}


