package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Countvalue generated by hbm2java
 */
@Entity
@Table(name="countvalue"
)
public class Countvalue  implements java.io.Serializable {


     private long observationid;
     private Integer value;

    public Countvalue() {
    }

	
    public Countvalue(long observationid) {
        this.observationid = observationid;
    }
    public Countvalue(long observationid, Integer value) {
       this.observationid = observationid;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="observationid", unique=true, nullable=false)
    public long getObservationid() {
        return this.observationid;
    }
    
    public void setObservationid(long observationid) {
        this.observationid = observationid;
    }

    
    @Column(name="value")
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }




}


