// package it.sinergis.sunshine.sos40.pojo;
// // Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1
//
//
// import javax.persistence.AttributeOverride;
// import javax.persistence.AttributeOverrides;
// import javax.persistence.Column;
// import javax.persistence.EmbeddedId;
// import javax.persistence.Entity;
// import javax.persistence.Table;
//
// /**
// * GeometryColumns generated by hbm2java
// */
// @Entity
// @Table(name="geometry_columns"
// )
// public class GeometryColumns implements java.io.Serializable {
//
//
// private GeometryColumnsId id;
//
// public GeometryColumns() {
// }
//
// public GeometryColumns(GeometryColumnsId id) {
// this.id = id;
// }
//
// @EmbeddedId
//
//
// @AttributeOverrides( {
// @AttributeOverride(name="FTableCatalog", column=@Column(name="f_table_catalog", length=256) ),
// @AttributeOverride(name="FTableSchema", column=@Column(name="f_table_schema", length=256) ),
// @AttributeOverride(name="FTableName", column=@Column(name="f_table_name", length=256) ),
// @AttributeOverride(name="FGeometryColumn", column=@Column(name="f_geometry_column", length=256) ),
// @AttributeOverride(name="coordDimension", column=@Column(name="coord_dimension") ),
// @AttributeOverride(name="srid", column=@Column(name="srid") ),
// @AttributeOverride(name="type", column=@Column(name="type", length=30) ) } )
// public GeometryColumnsId getId() {
// return this.id;
// }
//
// public void setId(GeometryColumnsId id) {
// this.id = id;
// }
//
//
//
//
// }
//
//
