package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Geometryvalue generated by hbm2java
 */
@Entity
@Table(name="geometryvalue"
)
public class Geometryvalue  implements java.io.Serializable {


     private long observationid;
     private Serializable value;

    public Geometryvalue() {
    }

	
    public Geometryvalue(long observationid) {
        this.observationid = observationid;
    }
    public Geometryvalue(long observationid, Serializable value) {
       this.observationid = observationid;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="observationid", unique=true, nullable=false)
    public long getObservationid() {
        return this.observationid;
    }
    
    public void setObservationid(long observationid) {
        this.observationid = observationid;
    }

    
    @Column(name="value")
    public Serializable getValue() {
        return this.value;
    }
    
    public void setValue(Serializable value) {
        this.value = value;
    }




}


