package it.sinergis.sunshine.sos40.pojo;

// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Offeringallowedfeaturetype generated by hbm2java
 */
@Entity
@Table(name = "offeringallowedfeaturetype")
public class Offeringallowedfeaturetype implements java.io.Serializable {
	
	private long id;
	
	public Offeringallowedfeaturetype() {
	}
	
	public Offeringallowedfeaturetype(long id) {
		this.id = id;
	}
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "offering", column = @Column(name = "offeringid", nullable = false)),
			@AttributeOverride(name = "featureofinteresttype", column = @Column(name = "featureofinteresttypeid", nullable = false)) })
	public long getId() {
		return this.id;
	}
	
	public void setId(long id) {
		this.id = id;
	}
	
}
