package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhenomenonTimestart generated by hbm2java
 */
@Entity
@Table(name="phenomenon_timestart"
)
public class PhenomenonTimestart  implements java.io.Serializable {


     private Date phenomenontimestart;

    public PhenomenonTimestart() {
    }

    public PhenomenonTimestart(Date phenomenontimestart) {
       this.phenomenontimestart = phenomenontimestart;
    }
   
     @Id 

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="phenomenontimestart", length=29)
    public Date getPhenomenontimestart() {
        return this.phenomenontimestart;
    }
    
    public void setPhenomenontimestart(Date phenomenontimestart) {
        this.phenomenontimestart = phenomenontimestart;
    }




}


