package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Relatedfeature generated by hbm2java
 */
@Entity
@Table(name="relatedfeature"
)
public class Relatedfeature  implements java.io.Serializable {


     private long relatedfeatureid;
     private Featureofinterest featureofinterest;
     private Set offeringhasrelatedfeatures = new HashSet(0);
     private Set relatedfeaturehasroles = new HashSet(0);

    public Relatedfeature() {
    }

	
    public Relatedfeature(long relatedfeatureid, Featureofinterest featureofinterest) {
        this.relatedfeatureid = relatedfeatureid;
        this.featureofinterest = featureofinterest;
    }
    public Relatedfeature(long relatedfeatureid, Featureofinterest featureofinterest, Set offeringhasrelatedfeatures, Set relatedfeaturehasroles) {
       this.relatedfeatureid = relatedfeatureid;
       this.featureofinterest = featureofinterest;
       this.offeringhasrelatedfeatures = offeringhasrelatedfeatures;
       this.relatedfeaturehasroles = relatedfeaturehasroles;
    }
   
     @Id 

    
    @Column(name="relatedfeatureid", unique=true, nullable=false)
    public long getRelatedfeatureid() {
        return this.relatedfeatureid;
    }
    
    public void setRelatedfeatureid(long relatedfeatureid) {
        this.relatedfeatureid = relatedfeatureid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="featureofinterestid", nullable=false)
    public Featureofinterest getFeatureofinterest() {
        return this.featureofinterest;
    }
    
    public void setFeatureofinterest(Featureofinterest featureofinterest) {
        this.featureofinterest = featureofinterest;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unresolved")
    public Set getOfferinghasrelatedfeatures() {
        return this.offeringhasrelatedfeatures;
    }
    
    public void setOfferinghasrelatedfeatures(Set offeringhasrelatedfeatures) {
        this.offeringhasrelatedfeatures = offeringhasrelatedfeatures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unresolved")
    public Set getRelatedfeaturehasroles() {
        return this.relatedfeaturehasroles;
    }
    
    public void setRelatedfeaturehasroles(Set relatedfeaturehasroles) {
        this.relatedfeaturehasroles = relatedfeaturehasroles;
    }




}


