package it.sinergis.sunshine.sos40.pojo;
// Generated 3-feb-2015 15.58.44 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Relatedfeaturerole generated by hbm2java
 */
@Entity
@Table(name="relatedfeaturerole"
    , uniqueConstraints = @UniqueConstraint(columnNames="relatedfeaturerole") 
)
public class Relatedfeaturerole  implements java.io.Serializable {


     private long relatedfeatureroleid;
     private String relatedfeaturerole;
     private Set relatedfeaturehasroles = new HashSet(0);

    public Relatedfeaturerole() {
    }

	
    public Relatedfeaturerole(long relatedfeatureroleid, String relatedfeaturerole) {
        this.relatedfeatureroleid = relatedfeatureroleid;
        this.relatedfeaturerole = relatedfeaturerole;
    }
    public Relatedfeaturerole(long relatedfeatureroleid, String relatedfeaturerole, Set relatedfeaturehasroles) {
       this.relatedfeatureroleid = relatedfeatureroleid;
       this.relatedfeaturerole = relatedfeaturerole;
       this.relatedfeaturehasroles = relatedfeaturehasroles;
    }
   
     @Id 

    
    @Column(name="relatedfeatureroleid", unique=true, nullable=false)
    public long getRelatedfeatureroleid() {
        return this.relatedfeatureroleid;
    }
    
    public void setRelatedfeatureroleid(long relatedfeatureroleid) {
        this.relatedfeatureroleid = relatedfeatureroleid;
    }

    
    @Column(name="relatedfeaturerole", unique=true, nullable=false)
    public String getRelatedfeaturerole() {
        return this.relatedfeaturerole;
    }
    
    public void setRelatedfeaturerole(String relatedfeaturerole) {
        this.relatedfeaturerole = relatedfeaturerole;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unresolved")
    public Set getRelatedfeaturehasroles() {
        return this.relatedfeaturehasroles;
    }
    
    public void setRelatedfeaturehasroles(Set relatedfeaturehasroles) {
        this.relatedfeaturehasroles = relatedfeaturehasroles;
    }




}


